[resolves #14] Find user by name
eamquindio/devteam_2019II_mysupermarket-users-ms pull request #27
Opened 2019-08-08 15:51 UTC by Alvaro1050

2019-08-08 20:01 UTC, Daryl110 approved these changes
good job

2019-08-08 21:07 UTC, wartski1 approved these changes

2019-08-08 21:59 UTC, jhonquirama approved these changes
be safe

2019-08-08 22:43 UTC, jhonquirama requested changes
Please change query  to params in UserController thank you !!!

2019-08-08 22:47 UTC, Daryl110 approved these changes
good job

2019-08-08 22:47 UTC, jhonquirama approved these changes

2019-08-08 22:49 UTC, ndavila1 approved these changes

2019-08-10 01:45 UTC, ingesofteam commented on app/controllers/UsersController.js
> +
sobra salto de linea

2019-08-10 01:45 UTC, ingesofteam commented on app/repositories/UserRepository.js
> +
sobra salto de linea

2019-08-10 01:46 UTC, ingesofteam commented on app/services/UserService.js
> +
sobra enter

2019-08-10 01:47 UTC, ingesofteam commented on app/services/UserService.js
> +    console.log('findByName user')
salto de linea sobra

2019-08-10 01:48 UTC, ingesofteam commented
Este PR tiene un puntaje de 70/100

los que lo revisaron acumulan 15 puntos en la tarea de revision de PRs
@Daryl110 @ndavila1 @jhonquirama @wartski1

2019-08-10 02:34 UTC, 0670alejo approved these changes

2019-08-16 10:32 UTC, closed without merging